---

- hosts: all
  gather_facts: true
  remote_user: alex
  become: true
  become_method: sudo
  tasks:


  - name: add my temp subscription
    shell: subscription-manager register --org=11546460 --activationkey=build-labs-all --force
    tags:
      attach
  - name: attatch sub
    shell: subscription-manager attach --pool=8a85f99b6d6e1ad3016d82450d5b42d9
    tags:
      subs
  - name: add subs
    shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.11-rpms" --enable="rhel-7-server-ansible-2.6-rpms"
    tags:
      subs
  - name: import gpg keys 
    shell: yum install wget git net-tools bind-utils yum-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct redhat-upgrade-tool -y
  - name:
    shell: yum clean all  
  - yum:
      name: kernel
      state: latest
    tags:
      update
  - name: update yum
    yum:
      name: '*'
      state: latest
    tags:
      update
  
  - name: update /etc/hosts file
    become: true
    blockinfile:
      dest: /etc/hosts
      content: "{{ lookup('template', 'templates/etc_hosts.j2') }}"
      state: present
  

  - name: add peer dns to en1 
    lineinfile: 
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      regex: 'IPADDRESS'
      insertafter: 'IPADDRESS'
      line: 'DNS1=8.8.8.8'
    tags:
      fix_dns
 # - name: remove dnsmasq
 #   shell: yum -y remove dnsmasq ; rm -Rf /etc/dnsmasq
 #   tags:
 #     dns_masq
# - name: INSERT GOOgle DNS 
#    lineinfile: 
#      path: /etc/resolv.conf
##      regex: 'nameserver'
#      line: 'nameserver 8.8.8.8'
#    tags:
#      fix_dns

  - name: Put SELinux in targeted mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: enforcing
  - name: install packages
    yum:
      name:
        - wget
        - atomic
        - openshift-ansible
        - git
        - net-tools
        - bind-utils
        - yum-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct
        - docker-1.13.1
      state: present

  - name: reboot for changes
    command: reboot
    tags:
      reboot
  
